// Páginas
export const PURCHASE_PAGE_CREATE = '/purchase/create';
export const PURCHASE_PAGE_EDIT = '/purchase/edit';
// Endpoint
export const PURCHASE_URL_CREATE = 'purchase/create';
export const PURCHASE_URL_EDIT = 'purchase/:id/edit';
export const PURCHASE_URL_STORE = 'purchase';
export const PURCHASE_URL_UPDATE = 'purchase/:id';

export const PAYMENT_METHODS = {
	EFFECTIVE: 'EFFECTIVE_PAYMENT',
	CREDIT: 'CREDIT_PAYMENT'
};

export const PURCHASE_STATUS = {
	PURCHASE_STATUS_IN_PROCESS: 'PURCHASE_STATUS_IN_PROCESS',
	PURCHASE_STATUS_CHECKING: 'PURCHASE_STATUS_CHECKING',
	PURCHASE_STATUS_CANCELLED: 'PURCHASE_STATUS_CANCELLED',
	PURCHASE_STATUS_APPROVED: 'PURCHASE_STATUS_APPROVED',
	PURCHASE_STATUS_REJECTED: 'PURCHASE_STATUS_REJECTED',
	PURCHASE_STATUS_CLOSED: 'PURCHASE_STATUS_CLOSED',
	PURCHASE_STATUS_FINISHED: 'PURCHASE_STATUS_FINISHED'
};
